### ISSUE TITLE
.m3u8 AAC stream works on SMPlayer, but stream isn't identified by radiobrowser

### ISSUE THREAD

**Issue by anewuser** [segler-alex/radiobrowser#11]
I can't get Rádio Eldorado FM (http://estadao2-lh.akamaihd.net/i/1_1@135260/master.m3u8) to work with gradio.

Your website/project says that the stream is "unknown", even though it works on SMPlayer.

**Comment by segler-alex** [comment]
i added hls support to the server. the information from the server has an additional hls tag to mark the hls streams.
