### ISSUE TITLE
Error to play bandit rock

### ISSUE THREAD

**Issue by juanda-097** [segler-alex/radiobrowser#13]
Hi radiobrowser support team I have a problem with this link http://fm02-icecast.mtg-r.net/fm02_mp3 beacuse in the website not works, but in vlc works.

Thank you for your attention.

PD:yesterday if it worked

sorry for my English

**Comment by indr** [comment]
http://www.radio-browser.info/gui/#/byname/bandit%20rock

@segler-alex works fine for me.

**Comment by juanda-097** [comment]
Works fine please close this issue.

_Sent from my Motorola XT1650 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
