### ISSUE TITLE
Many radio stations in China do not work

### ISSUE THREAD

**Issue by spiral2k** [segler-alex/radiobrowser#132]
somebody have an idea why? maybe geoblock?

**Comment by zo-shin** [comment]
Could you specify what stations they are?

**Comment by MicroBeast** [comment]
I test by cherry pick any radio under China country category. Seem fine from my SE Asia country. Except, using play on community radio page seem not working on me (Firefox), maybe just super slow caching. I manage to play perfectly using VLC. So, try using external player.

**Comment by spiral2k** [comment]
There was a bug in odio https://github.com/odioapp/odio/issues/24

🙏
