### ISSUE TITLE
Some Stations Fail the Subsequent Online Check

### ISSUE THREAD

**Issue by zo-shin** [segler-alex/radiobrowser#142]
Some stations passed the initial online check when they were established, but failed the subsequent online checks every time. Two of them are listed as follows.
**Sony BBC Earth TV**
**_http://123.249.76.157:10018/bysid/73_**
**Shansi Satellite TV**
**_http://live1.sxrtv.com/flvss?bitrate=800000&channel=Shan1XiTV&start=0&provider=www.tvmining.com_**

**Comment by kekukui** [comment]
**srxtv.com** & **tvmining.com** really are offline.  **BBC one** seems to be working but it may not be stable.

**Comment by zo-shin** [comment]
Thanks for your attention, but the station you said was offline works well.

**Comment by kekukui** [comment]
I guess they are also geo-restricted
