### ISSUE TITLE
Bounce to HTTPS

### ISSUE THREAD

**Issue by kousu** [segler-alex/radiobrowser#155]
Typing "radio-browser.info" doesn't automatically bounce me to "https://radio-browser.info", even though https exists and works thanks to letsencrypt.

This is easy to setup now. If you're using nginx you can use this fragment:

```
    server {
        listen       80;

        # enforce https
        # if this is the only server { } we run on port 80, then *all* http connections get rewritten to https ones
        # ($host is pulled from the client's request, along with $request_uri, so this line works for *any* virtual host we care to make)
        location / {
            return 301 https://$host$request_uri;
        }
  }
```

**Comment by kousu** [comment]
I also like to use letsencrypt's webroot plugin instead of the nginx plugin because I think it's more reliable; for that, add this to that fragment:

```
        location /.well-known {
            alias /srv/http/.well-known;
        }
```

and set up letsencrypt to use that folder:

```
# systemctl restart nginx || service nginx restart
# mkdir -p /srv/http/
# certbot certonly --webroot -w /srv/http -d radio-browser.info
```

**Comment by sr0n** [comment]
Don’t know if this is how it has been implemented but it seems like this is the behaviour now, HTTP site is inaccessible

**Comment by Rondom** [comment]
https://radio-browser.info/ gives a certificate error, but https://www.radio-browser.info/ works.
