### ISSUE TITLE
Can't add Radio Kiss Kiss Italia

### ISSUE THREAD

**Issue by AlbertHilb** [segler-alex/radiobrowser#16]
Connection check for Radio Kiss Kiss Italia, http://wma06.fluidstream.net:3614, fails but that streaming works flawlessly with VLC.

**Comment by indr** [comment]
@AlbertHilb Works for me:

![image](https://cloud.githubusercontent.com/assets/849548/25043516/2cd50d66-2153-11e7-9d61-3a3ab8371ee8.png)

/cc @segler-alex

**Comment by AlbertHilb** [comment]
I can confirm. Now It works! :blush:
Closing.
