### ISSUE TITLE
Cannot add country

### ISSUE THREAD

**Issue by keunes** [segler-alex/radiobrowser#178]
Hello,

I discovered this repository through the new Odio app. Since my regional public broadcaster wasn't listed yet, I [added it](https://www.radio-browser.info/gui/#!/history/db2cb556-1f5d-11ea-a955-52543be04c81). I wanted to add the country, but I couldn't: I can type but when exiting the field it got emptied again (other fields remained filled/fine), pressing enter didn't do anything but empty the field and revert the custom favicon url I had set. I tried both in English and the native language.

I'm using Firefox 71.0 (64-bits) on Ubuntu 18.04.3.

Maybe the same as described in https://github.com/segler-alex/radiobrowser/issues/163#issuecomment-522245628?

**Comment by keunes** [comment]
On a side note: it would be great if the country (The Netherlands) could still be added to the listing 0:)

**Comment by ahyattdev** [comment]
I ran into this too. It is because angular tries to load a country list over HTTP and Firefox blocks that due to mixed content (loading HTTP resource from HTTPS webpage).

The workaround is to do this: https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox#w_unblock-mixed-content

and reload add page

**Comment by keunes** [comment]
Thanks for that workaround @ahyattdev! Hope that the core issue can stil be fixed,  though :)

**Comment by sr0n** [comment]
Can confirm this happens in Edge & Chrome as well as Firefox, which displays the message: `Blocked loading mixed active content "http://restcountries.eu/rest/v2/name/united%20kingdom" angular.js:13630:6
`

Looks like it can be reached by HTTPS as well: https://restcountries.eu/rest/v2/name/united%20kingdom

Another workaround for now is just to load the HTTP page: http://www.radio-browser.info/gui/#!/add

**Comment by sr0n** [comment]
@segler-alex If I am right, this issue is fixed now & can be closed.
