### ISSUE TITLE
After fixing a station, cannot eliminate the "broken" tag

### ISSUE THREAD

**Issue by bidaian** [segler-alex/radiobrowser#179]
The technicians at [Euskalerria Irratia](https://euskalerriairratia.eus/) fixed the issue with their streaming (that also affected their webpage widget).

Now it is working, but I don't see how to remove the tag. Should I add a new station under the same name?

**Comment by segler-alex** [comment]
if it does not fix itsself after 24 hours, please add it again with the correct link. auto check of every stream is done every 24 hours.

**Comment by bidaian** [comment]
Thanks! It was fixed automatically.
