### ISSUE TITLE
SomaFM Groove Salad

### ISSUE THREAD

**Issue by Wikinaut** [segler-alex/radiobrowser#20]
Hi,

I found many times in the past, that the stream Url (in radio-browser.info) was changed from 
http://somafm.com/groovesalad.pls to http://somafm.com/groovesalad130.pls 

The ....130.pls is not working (on the Android).
Currently, I have no idea what is going on.

Can we have a "list of recent changes", I mean like in Wikipedia related to a station the "log of changes" ?

**Comment by Wikinaut** [comment]
@segler-alex pls. check, why the (incorrect) stream url groovesalad130.pls reappears after my recent (I think) 3 or 4 changes to the (correct) groovesalad.pls address.

**Comment by Wikinaut** [comment]
All SomaFM stations appear to be broken. I tried to fix some, but currently without success.

**Comment by segler-alex** [comment]
a curl request from the commandline to any soma fm station from the server does not work.
while the same request from my home machine does. i think they block me....

**Comment by Wikinaut** [comment]
Perhaps you have seen, that all SomaFM stations are marked "broken"  now.

Can I suggest to you
* temporarily stop the automatic checking of the SomaFM stations.

Perhaps this relatively new code (on your server) is firing to many, or wrongly looking requests ?

I will contact the SomaFM staff, perhaps you have seen that this is a community radio station which "lives" from donations. Once I donated to them and will try to check now (contact by mail) what they have changed and perhaps ask to revert the changes.

Would like to have the SomaFM channels back in the list and working.

**Comment by Wikinaut** [comment]
On my MacBook, the pls stream is opened and working in iTunes. Why not in the RadioDroid App ? Perhaps a code bug (regression) ?

**Comment by segler-alex** [comment]
yes we got blocked. please see:
https://github.com/segler-alex/radiobrowser/issues/20#issuecomment-276402550

**Comment by Wikinaut** [comment]
@segler-alex Have you got information from the Soma staff ? I do not understand, how (and still doubt that they really block us) they can block both the web interface on radio-browser.info _and_ "my" Android fetching the stream. I think, my Android cannot be detected by them.

Or is there something "behind the curtain" in the code ?
