### ISSUE TITLE
 Problems to play streams with extension .m3u8

### ISSUE THREAD

**Issue by Caballlero** [segler-alex/radiobrowser#21]
i test with vlc , it is woking fine.
It would be nice if you support streaming with extension .m3u8

**Comment by segler-alex** [comment]
it should work since a few weeks. i forgot to close this issue.

**Comment by Caballlero** [comment]
thanks = )

**Comment by carlosgonzz** [comment]
Hello again. I need access to edit radio station of my country, I need fix lot of thing. Also m3u8 is not supported even in your app RadioDroid which I tested. I using sailfish os with allradio-app which is radio-community-browser client but is not supporting m3u8 ither, I already open a feature request in allradio to support HLS. On my country lot of radio station they are transmiting in HLS, then I want to know if HLS can be add at radio-community-browser client without issues. Also I want to know if HLS client is a correct extension to be added a radio-community-source. 
thanks of advance
