### ISSUE TITLE
Virgin Radio Calgary aka CIBK 98.5 "Virgin Radio" Calgary, AB

### ISSUE THREAD

**Issue by retrorich75** [segler-alex/radiobrowser#22]
Extract url for aac from http://www.iheartradio.ca/virginradio/calgary

http://17943.live.streamtheworld.com/CIBKFMAAC.aac

Plays in VLC 2.2.4 on Windows 10

**Comment by segler-alex** [comment]
i think this station is geoblocked, i cannot play it myself from austria, sorry :(
