### ISSUE TITLE
Adding station, but never appears 

### ISSUE THREAD

**Issue by fourofspades** [segler-alex/radiobrowser#226]
It's quite an openended process. No feedback.  Perhaps an optional email address for result of the addition to be sent to.

I have added a station twice, pretty sure it was valid, but it neever appears.  No idea what the issue is.

**Comment by fourofspades** [comment]
Tried again today, no luck again.  Here is what I am submitting.  What am I doing wrong?  (I tried a different missing stream, and that didn't add either).

![air](https://user-images.githubusercontent.com/61576868/97205282-286ed580-17af-11eb-8e11-ec7f2b87a5ab.png)

**Comment by fourofspades** [comment]
Stream URL: https://stream.air1072.com/high

**Comment by ahyattdev** [comment]
Press ENTER to make english a tag. it should look like "community radio" and "dorset" do there.

**Comment by fourofspades** [comment]
Nope, tried again after entering the seemingly optional language tag, no different.  Still no dice.  Tried a different stream again, also never appeared.

Feedback Radio

Stream:   https://streaming02.zfast.co.uk/proxy/feedback?mp=/stream?ver=316427

Logo: https://pbs.twimg.com/profile_images/1126732968989356032/gZg6HojG_400x400.jpg

![Screenshot_20201027_074406_com android chrome](https://user-images.githubusercontent.com/61576868/97271298-4c223200-1828-11eb-8fe3-da1b95faf771.jpg)

**Comment by sr0n** [comment]
This is happening for me as well, on Firefox. Tried adding a station twice now and it never appears on the website or in Radiolise. Normally the page it takes you to after is a list of the latest added stations with "pending" or something similar, and the one you just added is at the top but that isn't happening now.

My stream is definitely working:

Hits Radio (Suffolk)
https://stream-mz.planetradio.co.uk/net1suffolk.aac

**Comment by fourofspades** [comment]
Is this a dead project?  Anyone know if it's actively maintained?

**Comment by sr0n** [comment]
@fourofspades Just tried to add a station via the HTTPS site and it seems to be working, and that bug where language and country selection wasn’t working on the HTTPS site seems to be fixed now too.

And it seems HTTP now redirects to HTTPS now too

**Comment by fourofspades** [comment]
Can confirm all stations that failed to add now add correctly
