### ISSUE TITLE
PullServers issues

### ISSUE THREAD

**Issue by Saddamus** [segler-alex/radiobrowser#232]
Hello
What does this log mean and what action should be taken ?
![image](https://user-images.githubusercontent.com/7191172/100268406-49b11600-2f55-11eb-9283-9e67c459290c.png)
This is latest docker image.

**Comment by segler-alex** [comment]
i think i need more information from you what you are actually running, and how you started it and how you configured it.
you are running your own instance of radiobrowser-api-rust? 
it ssems that your configuration is wrong, you should never pull from api.radio-browser.info directly, but from a fixed server like nl1.api.radio-browser.info for example. api.radio-browser.info is only usable without https

**Comment by Saddamus** [comment]
Thank you for your response.
I have deployed docker image: segleralex/radiobrowser-api-rust  with kubernetes.
All settings were default except : `[pullservers.alpha]
host = "https://api.radio-browser.info"`
because of this information:
> If you still use the api at www.radio-browser.info/webservice you should switch as soon as possible to the new one at api.radio-browser.info. The old one is not supported anymore and will not receive any more updates on the software side. The new one is in place and stronger than ever (multiple servers). The api endpoints at www.radio-browser.info/webservice will be taken down at August 1. of 2020.

**Comment by segler-alex** [comment]
cool, never tried it in kubernetes. but you need to use a single node that you pull from: basically one of
de1.api.radio-browser.info
nl1.api.radio-browser.info
fr1.api.radio-browser.info

**Comment by Saddamus** [comment]
Works as single instance. 
![image](https://user-images.githubusercontent.com/7191172/100282603-35c4de80-2f6c-11eb-91c4-04df8900cab3.png)
After changing address, it filled database with stations, so seems to work fine :)
I have created helm chart, but its not finished - need to template config and mount as volume, something like this:
`volumes:
  - name: radioconfig
    configMap:
      name: radioconfig
volumeMounts:
  - name: radioconfig
    mountPath: /etc/radiobrowser.toml
    subPath: radioconfig`
after that I can share with you.
Looks like you need to update your docker image because of this out of date API address in config file.

**Comment by Saddamus** [comment]
Hello,
The problem for some reason is back.
![image](https://user-images.githubusercontent.com/7191172/100431193-1a56f200-3098-11eb-856f-7b5b1c73c99b.png)
Do you have ability to deploy my helm chart on kubernetes ?
I think it would be a benefit also for you to have working kubernetes deployment :)

**Comment by segler-alex** [comment]
i created now my own official helm chart
https://gitlab.com/radiobrowser/helm-charts
