### ISSUE TITLE
website player links to https while the URL should be http

### ISSUE THREAD

**Issue by grinapo** [segler-alex/radiobrowser#238]
Tried [this station](https://www.radio-browser.info/#!/history/961f4d61-0601-11e8-ae97-52543be04c81) for example and it cannot play (neither on Firefox nor Chromium) since the site tries to connect to `https://stream addr` while the database entry contains the proper `http://` links. 
While I am not sure mixed content would load but connecting to a http port using TLS surely won't work either.

**Comment by segler-alex** [comment]
this is just an index of streams of other people.
providers of streams do decide if they provide https and/or http
we cannot do anything about that
