### ISSUE TITLE
Cannot play Yabiladi or Dojo Weiterswiller

### ISSUE THREAD

**Issue by dalb8** [segler-alex/radiobrowser#24]
Stations that I added recently

**Comment by indr** [comment]
@dalb8 [Yabiladi](http://www.radio-browser.info/gui/#/edit/92841) works fine. I can't find Dojo Weiterswiller, not even on the web. Do you have link?

**Comment by dalb8** [comment]
http://www.radio-browser.info/gui/#/byname/dojo.

It's silent most of the time , I know.

**Comment by indr** [comment]
http://www.radio-browser.info/gui/#/byname/yabiladi

@dalb8 So the two stations can be played and we can close this issue @segler-alex ?
