### ISSUE TITLE
FR: Pls/m3u download

### ISSUE THREAD

**Issue by gerroon** [segler-alex/radiobrowser#25]
Hi

Can you please provide up to date pls/m3u downloads of the whole radio list? Not everyone is developer and this would be an easy way to access to whole list at once, the playlists can then be easily imported into the listener's favorite listening program and be searched etc.

**Comment by segler-alex** [comment]
Thank you for this idea, i just implemented support for M3U, PLS and XSPF output formats.
For example you can do something like
http://www.radio-browser.info/webservice/pls/stations/topclick/5

**Comment by gerroon** [comment]
@segler-alex 

Thanks for taking the lead on this. I will test it out.
