### ISSUE TITLE
Missing escaping in json/url/{station_id}

### ISSUE THREAD

**Issue by sfuhrm** [segler-alex/radiobrowser#37]
I get a result json like this:

`[{"ok":"true","message":"retrieved station url successfully","id":"95814","name":"101.ru - Viktor Tsoi and "Kino" band","url":"http://ic7.101.ru:8000/a103"}]`

from the webservice url

http://www.radio-browser.info/webservice/json/url/95814

or

http://www.radio-browser.info/webservice/json/url/96081

which violates the resulting JSON.

As you can see, the `"Kino"` part in the string above also contains double quotes.

**Comment by segler-alex** [comment]
as i said in https://github.com/segler-alex/radiobrowser/issues/38
i cannot reproduce this behaviour

**Comment by sfuhrm** [comment]
This was also a missing v2 in url topic. Sorry for bothering you.
