### ISSUE TITLE
Wrong API doc for json/url/{station_id}

### ISSUE THREAD

**Issue by sfuhrm** [segler-alex/radiobrowser#38]
The API says to return a simple object

>Playable station url
>
>Syntax:
>http://www.radio-browser.info/webservice/v2/xml/url/stationid 
>http://www.radio-browser.info/webservice/v2/json/url/stationid 
>http://www.radio-browser.info/webservice/v2/pls/url/stationid 
>http://www.radio-browser.info/webservice/v2/m3u/url/stationid
>Description:
>Returns the playable url for the station.
>Any Playlist (PLS, ASX, M3U) decoding will be done for you.
>This API call will count as a click on the station.
>Supported output formats: json,xml,pls(playlist),m3u(playlist) 
>Result JSON:
>{
> "ok": "true",
>  "message": "retrieved station url",
>  "id": "123",
>  "name": "Station name",
>  "url": "http://this.is.an.url"
>}`

But what's actually returned is an array:

`[{"ok":"true","message":"retrieved station url successfully","id":"95814","name":"101.ru - Viktor Tsoi and "Kino" band","url":"http://ic7.101.ru:8000/a103"}]`

**Comment by segler-alex** [comment]
with what program did you check that? i cannot reproduce this. for me it is exactly like the documentation says.

curl -v http://www.radio-browser.info/webservice/v2/json/url/95814
gives me the following
*   Trying 37.120.178.42...
* TCP_NODELAY set
* Connected to www.radio-browser.info (37.120.178.42) port 80 (#0)
> GET /webservice/v2/json/url/95814 HTTP/1.1
> Host: www.radio-browser.info
> User-Agent: curl/7.55.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sat, 26 Aug 2017 15:25:47 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: origin, x-requested-with, content-type
< Access-Control-Allow-Methods: GET,POST
< Content-Length: 160
< Content-Type: application/json
< 
* Connection #0 to host www.radio-browser.info left intact
{"ok":"true","message":"retrieved station url successfully","id":"95814","name":"101.ru - Viktor Tsoi and \"Kino\" band","url":"http:\/\/ic7.101.ru:8000\/a103"}

**Comment by sfuhrm** [comment]
When I open the URL 

http://www.radio-browser.info/webservice/json/url/95814

in Chrome browser, I can see the `[]` array.

See the screen shot from Chrome here:

![bildschirmfoto vom 2017-08-26 17-41-55](https://user-images.githubusercontent.com/5055427/29742803-eea3656e-8a85-11e7-82ce-c8749298f661.png)

I used a Java Jersey client in my original program doing a call like this

```java
    private List<BUrlResponse> read(BStation bStation) {
                // http://www.radio-browser.info/webservice/v2/json/url/stationid 
        Response response = webTarget.path("url").path(bStation.id)
                .request(MediaType.APPLICATION_JSON_TYPE)
                .accept(MediaType.APPLICATION_JSON_TYPE)
                .header("User-Agent", MY_URL)
                .get();
        
        logger.debug("URI is {}", webTarget.getUri());
        if (response.getStatus() != 200) {
            logger.warn("Non 200 status: {} {}", response.getStatus(), response.getStatusInfo().getReasonPhrase());
            return Collections.emptyList();
        }
        return response.readEntity(new GenericType<List<BUrlResponse>>() {});
    }
```

Funny: With CURL i don't see the array [] markers.
