### ISSUE TITLE
Missing genres (tags)

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/radiobrowser#44]
These are listed:
* psychedelic
* psychedelic rock

# Missing psychedelic music genres to add

Psytrance sub genres:
* Darkpsy
* Hi-Tech
* Progressive psytrance
* Suomisaundi
* Psycore
* Psybreaks

Other genres of interest
* Acid rock
* Acid trance
* Italian occult psychedelia
* Neo-psychedelia
* Psychedelic folk
* Psychedelic funk
* Psychedelic hip hop
* Psychedelic pop
* Psychedelic soul
* Psydub

**Comment by davidhedlund** [comment]
These are listed:
* psychedelic
* psychedelic rock

Please add these tags:

* Acid trance
* Italian occult psychedelia
* Neo-psychedelia
* Psychedelic folk
* Psychedelic funk
* Psychedelic pop
* Psychedelic soul
* Psydub

**Comment by davidhedlund** [comment]
@segler-alex What can I do to add new genres?

**Comment by 0ttoman** [comment]
just add them. But please be sure the tags have relevance for other stations too.
It also reads "Please press ENTER or click ✓after every single tag to add them!" when you try to add new tags. So this should be apparent.
About your "Other genres of interest" - I don't know if "Psychedelic folk" is the way to tag. Separating them might make them easier to find but also could make it too vague. So please refer to already existing tags.

**Comment by davidhedlund** [comment]
@0ttoman Thanks.
