### ISSUE TITLE
Urgent: Undelete broken (sample will expire in 30 days)

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/radiobrowser#48]
Something trigger radio-browser.info to delete Psychedelik.com (playlist ID 101264) as soon as I undelete it. What is causing this?

http://www.radio-browser.info/gui/#/deleted says
> Stations in this list will be deleted completely after 30 days automatically.

so I provide a copy of the data here so we can use it later.
* Name: Psychedelik.com
* URL: http://195.154.166.226:8000/ -- used to be http://195.154.166.226:8000/; (note the semicolon), this might cause the problem.
* Homepage: https://www.psychedelik.com/

The tag is
> DUPLICATE OF: psychedelik.com - Psytrance

But the playlist is not in http://www.radio-browser.info/gui/#/bytag/psytrance

**Comment by davidhedlund** [comment]
http://www.radio-browser.info/gui/#/deleted says

> Stations in this list will be deleted completely after 30 days automatically.

So can you please have a look on this ASAP @segler-alex ?

**Comment by davidhedlund** [comment]
I provided a copy of the data on this issue so the playlist can expire if you don't have time.

**Comment by 0ttoman** [comment]
because it is a duplicate of http://www.radio-browser.info/gui/#/edit/55165 
That's why the tag is "DUPLICATE OF:"

**Comment by davidhedlund** [comment]
@0ttoman Thanks.
