### ISSUE TITLE
Should we rename "Country" to "Country (IP)" and disable manual editing?

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/radiobrowser#50]
I discovered that the "Country" field is automatically filled, I guess your cronjob figure out the country IP address and add the appropriate country to the playlist. Is this true?

If it is true, why can I fill "Country" at all? If its true, then I think it should be renamed to "Country (IP)" and that "Country" should be removed from http://www.radio-browser.info/gui/#/add and the edit page for the playlists, and only be filled/overwritten by your cronjob.

**Comment by segler-alex** [comment]
the country field is definitely NOT automatically filled.
why do you think that?????

**Comment by davidhedlund** [comment]
@segler-alex Because they were filled within hours after I submitted them. I guess they landed in http://www.radio-browser.info/gui/#/improve and were improved by the community then.
