### ISSUE TITLE
Stations with same names

### ISSUE THREAD

**Issue by ozzymanborn** [segler-alex/radiobrowser#55]
in the application I'm using in ubuntu (internet radio gnome shell extension) just capable to search by name (no country etc) . That's why I'm using distinctive sign if I saw wikipedia page of that radio. But of course people can change the names. And usually deleting distinctive info like callsign - frequency and county / city.
An Example: Radio City (italy/ 3 different radio , liverpool, maribor/slovenia, finland/nearly 10 radio, india/an internet radio portal and 10 different web radio) all having same name in different cities / countries.

**Comment by segler-alex** [comment]
please file this feature request on the project for the shell extension,
i think it is https://github.com/hslbck/gnome-shell-extension-radio
