### ISSUE TITLE
Yet Another Smooth Scrolling WE shows the player when it's not used

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/radiobrowser#65]
Yet Another Smooth Scrolling WE trigger the we player at radiobrowser.info (example: http://www.radio-browser.info/gui/#/bycodec/AAC) be temporary displayed ("Player active") when you scroll to the bottom of the page even if you don't use the player at all.

**Comment by segler-alex** [comment]
it works. i just tried it with deutschlandfunk. how can i reproduce your error? which browser do you have? greetings

**Comment by davidhedlund** [comment]
@segler-alex Thanks, it was a bug in a Firefox add-on. I reported this to the author.
