### ISSUE TITLE
DELETE, UNDELETE and REVERT are HIDDEN for now

### ISSUE THREAD

**Issue by davidhedlund** [segler-alex/radiobrowser#67]
* I deleted a station for test purpose that I was going to restore. I can press the Delete button but it isn't deleted from the database.
* [http://www.radio-browser.info/gui/#/deleted Deleted] is totally empty.

**Comment by segler-alex** [comment]
There is a message on http://www.radio-browser.info/gui/#/
i deactivated delete, revert and undelete. i got a disturbing message from a user who reported, that the wrong stations got deleted.
i did not find the cause yet, but i am also working on a complete rewrite for a few weeks now. i want to port the apache/php part to rust. mainly for speed, type checks. it will have compatible API calls.
but i also want to support multi server sync in the future to keep up with demand.
that is why i did not spend too much time with finding the bug.
why did you want to delete the station? did you have similiar experiences with wrong stations deleted in the past?

**Comment by davidhedlund** [comment]
> i did not find the cause yet, but i am also working on a complete rewrite for a few weeks now. i want to port the apache/php part to rust. mainly for speed, type checks. it will have compatible API calls.

I'm glad to hear this, I wish you all the best.

> why did you want to delete the station? did you have similiar experiences with wrong stations deleted in the past?

I wanted to delete (with the intention to use the **Undelete** function later) the station to [verify](https://github.com/segler-alex/RadioDroid/issues/138) an old bug that I submitted. There's nothing to worry about here, I just want to maintain my bug reports. I'm a developer too.

**Comment by davidhedlund** [comment]
Can you please temporarily hide
* The "Delete" button from edit mode ([example](http://www.radio-browser.info/gui/#/edit/96933) page)
* Top menu: "Needs help" -> "[Deleted](http://www.radio-browser.info/gui/#/deleted)"

**Comment by segler-alex** [comment]
this is a good idea, done

**Comment by davidhedlund** [comment]
Thank you. Optionally modify the text in http://www.radio-browser.info/gui/#/ to:

> DELETE,UNDELETE and REVERT are DISABLED for now

to something like

DELETE,UNDELETE and REVERT are HIDDEN for now

**Comment by davidhedlund** [comment]
First things to delete when the delete functions has been restored: http://www.radio-browser.info/gui/#/bytag/duplicate

**Comment by davidhedlund** [comment]
You have added back the Delete. Thank you.

I think you want to remove the text from the main page http://www.radio-browser.info/gui/#/ :
>  UNDELETE and REVERT are DISABLED for now. It caused some data corruption which is still beeing investigated.

And remove the red font color for this text:
>  ADD, EDIT and VIEW is still online and can be used without problems.

**Comment by davidhedlund** [comment]
Please close this issue once you've done that.

**Comment by davidhedlund** [comment]
Can you please do that? It's possible that http://www.radio-browser.info/gui/#/bytag/duplicate is building up because people might still think that it's not possible to delete stations.

**Comment by davidhedlund** [comment]
I fixed all "duplicate" tagged stations (removed duplicated, and removed the "duplicate" tag from non-duplicated stations).

So please fix https://github.com/segler-alex/radiobrowser/issues/67#issuecomment-374932543, because it's possible that http://www.radio-browser.info/gui/#/bytag/duplicate is building up because people might still think that it's not possible to delete stations.

I don't want more work than necessary.

**Comment by davidhedlund** [comment]
Fixed, thank you.
