### ISSUE TITLE
Failing on MSNBC, CNN, and CBS streams

### ISSUE THREAD

**Issue by rogersachan** [segler-alex/radiobrowser#86]
I've attempted to add all of these streams, as they all work within VLC all over the world without issue. Yet somehow, they don't even work. I think this is incorrect behavior because CBS uses a streamtheworld URL. There are all sorts of streamtheworld urls working absolutely fine in radiobrowser.

I'd appreciate any help if possible

Best Regards,
Roger

**Comment by segler-alex** [comment]
could you post the stream adresses? then i will check them when i come home from work.

**Comment by segler-alex** [comment]
thanks for your help.

MSNBC  seems to work at the moment.

i tried to play CBS (http://provisioning.streamtheworld.com/pls/CBSNEWS.pls) but this did not work for me. i got HTTP 403 Forbidden. :( i think it is geoblocked.

CNN (http://tunein.streamguys1.com/cnn) does not work too for me. i get a HTTP 401 Authentication required.

**Comment by rogersachan** [comment]
I had figured that geoblocking/authentication was an issue. Thanks for looking into this.

**Comment by kekukui** [comment]
Reference bug #147
